# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# GCR portion: https://cloud.google.com/architecture/creating-a-cicd-pipeline-azure-pipelines-cloud-run

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build App and Container
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      displayName: Maven Package
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: Build and Push Docker Image to ACR
      inputs:
        containerRegistry: 'ACR - scottmccrory'
        repository: 'scottmccrory/java-11-test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'