# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      displayName: Maven Package
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'ACR - scottmccrory'
        repository: 'scottmccrory/java-11-test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Pay-As-You-Go(2094ef89-09da-4eda-97c3-81392adc5f6d)'
        appName: 'java-11-test'
        containers: 'scottmccrory.azurecr.io/scottmccrory/java-11-test:latest'