# =============================
# Kubernetest deployment script
# =============================
# Created with:
#   kubectl create deployment java-11-test --image=scottmccrory/java-11-demo --dry-run -o=yaml > deployment.yaml
#   echo --- >> deployment.yaml
#   kubectl create service clusterip java-11-test --tcp=8081:8081 --dry-run -o=yaml >> deployment.yaml
# Deployed with:
#   kubectl apply -f deployment.yaml
# Status checked with:
#   kubectl get all -o wide
# Proxied with:
#   kubectl port-forward svc/java-11-test 8081:8081
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-11-test
  name: java-11-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-11-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-11-test
    spec:
      containers:
      - image: scottmccrory/java-11-test
        name: java-11-test
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-11-test
  name: java-11-test
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-11-test
  type: ClusterIP
status:
  loadBalancer: {}
