pipeline {

    environment {
      registry = "scottmccrory/java-11-test"
      dockerfile = "./deployment/docker/Dockerfile"
      registryCredential = 'dockerhub'
    } 

    // See https://www.edureka.co/community/55640/jenkins-docker-docker-image-jenkins-pipeline-docker-registry
    agent { label 'docker' }

    stages {

        stage('Get Application Sources') {

            steps {
                git 'https://github.com/rudderfeet/java-11-test.git'
            }

        }

        stage('Build and Test Application') {

            tools {
                maven 'Maven3'
            }

            steps {
                sh 'mvn clean verify'
            }

        }

        stage('Build Docker Image') {

            steps {
                script {
                    docker.build(registry, "-f ${dockerfile} .")
                }
            }

        }

        stage('Deploy Docker Image') {

            steps {

                script {
                    docker.withRegistry('', registryCredential ) {
                        sh "docker push $registry"
                    }
                }

            }

        }

        stage('Remove Unused Docker Image') {

            steps{
                sh "docker rmi $registry"
            }

        }

        stage('Apply deployment to k3s cluster') {

            steps{
                sh "./deployment/kubectl/kube-apply-java-11-test.sh"
            }

        }

    }

}